from __future__ import annotations

import statistics

from flask import Flask, jsonify, request


app = Flask(__name__)


@app.get("/")
def index():
    return (
        jsonify(
            {
                "service": "anomaly-detection",
                "status": "ok",
                "endpoints": {
                    "detect": {
                        "path": "/detect",
                        "method": "POST",
                        "modes": {
                            "zscore": {
                                "required_fields": [
                                    "method",
                                    "current_cases",
                                    "historical_mean",
                                    "std_dev",
                                ]
                            },
                            "arima": {
                                "required_fields": [
                                    "method",
                                    "current_cases",
                                    "historical_series",
                                ],
                                "optional_fields": [
                                    "arima_order",
                                    "anomaly_threshold",
                                ],
                            },
                        },
                    }
                },
            }
        ),
        200,
    )


def detect_with_zscore(
    current_cases: float, historical_mean: float, std_dev: float
) -> dict[str, float | str]:
    if std_dev <= 0:
        raise ValueError("std_dev must be greater than 0")

    z_score = (current_cases - historical_mean) / std_dev
    status = "ANOMALY" if z_score > 2 else "NORMAL"

    return {"z_score": z_score, "status": status}


def detect_with_arima(
    current_cases: float,
    historical_series: list[float],
    order: tuple[int, int, int],
    threshold: float,
) -> dict[str, float | str]:
    if len(historical_series) < 8:
        raise ValueError("historical_series must contain at least 8 values")

    if len(set(historical_series)) < 2:
        raise ValueError("historical_series must contain varying values")

    try:
        from statsmodels.tsa.arima.model import ARIMA
    except Exception as exc:
        raise RuntimeError(
            "ARIMA dependency missing. Install requirements.txt (statsmodels)."
        ) from exc

    model = ARIMA(historical_series, order=order)
    fitted_model = model.fit()
    forecast_next = float(fitted_model.forecast(steps=1)[0])

    residuals = [float(value) for value in fitted_model.resid]
    if len(residuals) < 2:
        raise ValueError("insufficient residuals generated by ARIMA model")

    burn_in = max(3, order[0] + order[1] + order[2])
    trimmed_residuals = residuals[burn_in:] if len(residuals) - burn_in >= 2 else residuals[1:]

    if len(trimmed_residuals) < 2:
        raise ValueError("insufficient post-burn-in residuals generated by ARIMA model")

    residual_std = float(statistics.pstdev(trimmed_residuals))
    if residual_std <= 0:
        raise ValueError(
            "ARIMA residual standard deviation is zero; cannot compute Z-score"
        )

    z_score = (current_cases - forecast_next) / residual_std
    status = "ANOMALY" if z_score > threshold else "NORMAL"

    return {
        "forecast_next": forecast_next,
        "residual_std": residual_std,
        "z_score": z_score,
        "status": status,
        "threshold": threshold,
    }


@app.post("/detect")
def detect():
    body = request.get_json(silent=True)
    if not isinstance(body, dict):
        return jsonify({"error": "Request body must be valid JSON"}), 400

    method = str(body.get("method", "zscore")).strip().lower()
    if method not in {"zscore", "arima"}:
        return jsonify({"error": "method must be either 'zscore' or 'arima'"}), 400

    if "current_cases" not in body:
        return jsonify({"error": "Missing required fields: current_cases"}), 400

    try:
        current_cases = float(body["current_cases"])
    except (TypeError, ValueError):
        return jsonify({"error": "current_cases must be numeric"}), 400

    if method == "zscore":
        required_fields = ("historical_mean", "std_dev")
        missing_fields = [field for field in required_fields if field not in body]
        if missing_fields:
            return (
                jsonify({"error": f"Missing required fields: {', '.join(missing_fields)}"}),
                400,
            )

        try:
            historical_mean = float(body["historical_mean"])
            std_dev = float(body["std_dev"])
        except (TypeError, ValueError):
            return (
                jsonify(
                    {
                        "error": "historical_mean and std_dev must be numeric"
                    }
                ),
                400,
            )

        try:
            result = detect_with_zscore(current_cases, historical_mean, std_dev)
        except ValueError as exc:
            return jsonify({"error": str(exc)}), 400

        response = {
            "method": "zscore",
            "input": {
                "current_cases": current_cases,
                "historical_mean": historical_mean,
                "std_dev": std_dev,
            },
            "z_score": round(float(result["z_score"]), 4),
            "classification": result["status"],
        }
    else:
        if "historical_series" not in body:
            return jsonify({"error": "Missing required fields: historical_series"}), 400

        historical_series_raw = body["historical_series"]
        if not isinstance(historical_series_raw, list) or len(historical_series_raw) == 0:
            return (
                jsonify({"error": "historical_series must be a non-empty numeric array"}),
                400,
            )

        try:
            historical_series = [float(item) for item in historical_series_raw]
        except (TypeError, ValueError):
            return (
                jsonify({"error": "historical_series must contain only numeric values"}),
                400,
            )

        order_raw = body.get("arima_order", [1, 1, 1])
        if (
            not isinstance(order_raw, list)
            or len(order_raw) != 3
            or not all(isinstance(v, int) and v >= 0 for v in order_raw)
        ):
            return (
                jsonify({"error": "arima_order must be an array of 3 non-negative integers"}),
                400,
            )

        order = (order_raw[0], order_raw[1], order_raw[2])

        threshold_raw = body.get("anomaly_threshold", 1.5)
        try:
            threshold = float(threshold_raw)
        except (TypeError, ValueError):
            return jsonify({"error": "anomaly_threshold must be numeric"}), 400

        if threshold <= 0:
            return jsonify({"error": "anomaly_threshold must be greater than 0"}), 400

        try:
            result = detect_with_arima(current_cases, historical_series, order, threshold)
        except ValueError as exc:
            return jsonify({"error": str(exc)}), 400
        except RuntimeError as exc:
            return jsonify({"error": str(exc)}), 500

        response = {
            "method": "arima",
            "input": {
                "current_cases": current_cases,
                "historical_series_count": len(historical_series),
                "arima_order": [order[0], order[1], order[2]],
            },
            "forecast_next": round(float(result["forecast_next"]), 4),
            "residual_std": round(float(result["residual_std"]), 4),
            "z_score": round(float(result["z_score"]), 4),
            "anomaly_threshold": float(result["threshold"]),
            "classification": result["status"],
        }

    return jsonify(response), 200


@app.get("/detect")
def detect_get_not_allowed():
    return (
        jsonify(
            {
                "error": "Method not allowed. Use POST /detect with JSON body.",
                "example": {
                    "method": "zscore",
                    "current_cases": 130,
                    "historical_mean": 100,
                    "std_dev": 10,
                },
                "arima_example": {
                    "method": "arima",
                    "current_cases": 130,
                    "historical_series": [
                        90,
                        95,
                        92,
                        98,
                        100,
                        102,
                        101,
                        99,
                        104,
                        107,
                    ],
                    "arima_order": [1, 1, 1],
                },
            }
        ),
        405,
    )


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
